# Generated by Django 5.2.7 on 2025-11-04 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('etiquetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at', '-updated_at', 'nombre', 'categoria', 'precio'],
            },
        ),
        migrations.CreateModel(
            name='DetallesProducto',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalles', serialize=False, to='producto.producto')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=8, null=True)),
                ('dimensiones', models.CharField(blank=True, help_text='Ej: 10x20x5 cm', max_length=100)),
            ],
            options={
                'verbose_name': 'Detalle del Producto',
                'verbose_name_plural': 'Detalles de Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de prioridad de la etiqueta (1 = más importante)')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_etiquetas', to='etiquetas.etiqueta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_etiquetas', to='producto.producto')),
            ],
            options={
                'verbose_name': 'Producto-Etiqueta',
                'verbose_name_plural': 'Productos-Etiquetas',
                'ordering': ['orden', 'fecha_asignacion'],
                'unique_together': {('producto', 'etiqueta')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.ManyToManyField(related_name='productos', through='producto.ProductoEtiqueta', to='etiquetas.etiqueta'),
        ),
    ]
